# Generated by Django 4.1 on 2022-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_alter_marque_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
